name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies for frontend
        run: cd frontend && npm install

      - name: Build frontend
        run: cd frontend && npm run dev

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend